go.modを1.25に修正してみる
```
go: downloading github.com/AlexBeauchemin/gobadge v0.4.0
go: github.com/AlexBeauchemin/gobadge@v0.4.0: github.com/AlexBeauchemin/gobadge@v0.4.0 requires go >= 1.23 (running go 1.22.2; GOTOOLCHAIN=local)
Error: Process completed with exit code 1.
```

github actionsで上記のようなログがでてしまった為。